const data = [
    {
        "id": "123456",
        "name": "ChatGPT",
        "description": "ChatGPT is an artificial intelligence chatbot developed by OpenAI that is capable of having human-like conversations. It can answer questions, provide information, and carry out tasks based on instructions.",
        "category": "Content Creation",
        "createdAt": 744163200000,
        "updatedAt": 1611014400000,
        "version": "4.0",
        "rating": 3.9,
        "website": "https://chat.openai.com/chat",
        "price": "Subscription",
        "tags": [
            "ChatGPT",
            "Artificial intelligence",
            "Natural language processing",
            "Conversational AI",
            "Chatbot",
            "Language model",
            "Machine learning",
            "OpenAI",
            "text generation",
            "dialogu"
        ],
        "image": "https://cdn.icon-icons.com/icons2/2108/PNG/512/chatgpt_logo_icon_130888.png",
        "features": [
            "Natural language processing",
            "Chatbot",
            "Language model",
            "Machine learning",
            "OpenAI",
            "text generation",
            "dialogu"
        ],
        "author": "ChatGPT is an artificial intelligence chatbot developed by OpenAI, which is a non-profit artificial intelligence research company founded in 2015 by a group of entrepreneurs and scientists. OpenAI is based in San Francisco, California, and is backed by a group of prominent investors, including Elon Mus",
        "bookmarked": false
    },
    {
        "id": "10413",
        "name": "Qbox",
        "description": "Qbox is a cloud-based AI platform that enables businesses to create, train, and deploy machine learning models.",
        "category": "Machine Learning",
        "createdAt": 1531958400000,
        "updatedAt": 1632355200000,
        "version": "2.0",
        "rating": 4.1,
        "website": "https://qbox.io/",
        "price": "Free",
        "tags": [
            "Machine Learning",
            "Predictive Analytics",
            "Deep Learning",
            "Computer Vision",
            "Natural Language Processing",
            "Text "
        ],
        "image": "https://ai-tools-data.s3.amazonaws.com/game-changers/qbox.png",
        "features": [
            " Data Preparation: Qbox provides tools for data preprocessing",
            "such as data cleaning",
            "feature engineering",
            "and data trans"
        ],
        "author": "Qbox Technologies Inc",
        "bookmarked": false
    },
    {
        "id": "910",
        "name": "ChatGPT",
        "description": "ChatGPT is an AI-powered chatbot that uses natural language processing to generate human-like responses to user input. It can be used for a variety of tasks, such as answering questions, generating content, and providing recommendations.",
        "category": "Machine Learning",
        "createdAt": 444960000000,
        "updatedAt": 1673740800000,
        "version": "1.4",
        "rating": 4.6666666667,
        "website": "https://openai.com/products/chatgpt",
        "price": "Paid",
        "tags": [
            "natural language processing",
            "machine learning",
            "language g"
        ],
        "image": "https://en.wikipedia.org/wiki/File:ChatGPT_logo_2022.png",
        "features": [
            "natural language processing",
            "machine learning",
            "language g"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "PH698-46",
        "name": "Video Generator AI",
        "description": "Video Generator AI helps you create high quality videos with a few clicks",
        "category": "Machine Learning",
        "createdAt": 1657670400000,
        "updatedAt": 1658534400000,
        "version": "2.0.2",
        "rating": 4.5,
        "website": "https://videogenerator.ai/",
        "price": "Paid",
        "tags": [
            "ideo generator",
            "AI video creation",
            "high quality videos",
            "video editing",
            "AI-powered",
            "video templates",
            "customize videos",
            "video marketing",
            "video editing software",
            "vide"
        ],
        "image": "https://ai-tools-cdn.vercel.app/api/tools/PH698-46/img.jpg",
        "features": [
            "High quality videos: Video Generator AI uses advanced AI algorithms to create high quality videos that are indistinguishable from those made by professional vide"
        ],
        "author": "Developer: Video Generator AI",
        "bookmarked": false
    },
    {
        "id": "4362903",
        "name": "ChatGPT",
        "description": "ChatGPT is a conversational AI assistant that can answer a wide range of questions and perform various tasks. It can help with research, writing, programming, and more.",
        "category": "Content Creation",
        "createdAt": 1604361600000,
        "updatedAt": 1652572800000,
        "version": "4.0",
        "rating": 4.4,
        "website": "https://openai.com/",
        "price": "Free",
        "tags": [
            "ChatGPT",
            "AI assistant'",
            "conversational AI'",
            "question answering'",
            "language processing'",
            "virtual assistant'",
            "natural language processing'",
            "c"
        ],
        "image": "https://openai.com/assets/img/openai-logo-dark@2x.png",
        "features": [
            "Prompt and Response",
            "Customization",
            "Integration with Other Tools",
            "Contextual Awareness",
            "Language Processing",
            "Question Answering",
            "Natural Language Processing",
            "Virtual Assistant",
            "Chatbot",
            "Prompt Engineering",
            "Language Generation",
            "Pers"
        ],
        "author": "Information about the creator or company behind the tool, with contact details",
        "bookmarked": false
    },
    {
        "id": "503",
        "name": "ChatGPT",
        "description": "ChatGPT is an AI tool that can be used to generate human-like responses to questions or prompts. It is capable of understanding natural language and generating relevant and coherent responses in a conversational manner.",
        "category": "Automation",
        "createdAt": -130291200000,
        "updatedAt": 1684108800000,
        "version": "2023-05-15 00:00:00",
        "rating": 4.3,
        "website": "https://chat.openai.com/chat",
        "price": "Free",
        "tags": [
            "AI",
            "chat",
            "text",
            "conversation",
            "natural language processing",
            "generative AI",
            "language model",
            "GPT-3",
            "GPT-4",
            "natural language understanding",
            "generative language model",
            "AI language model",
            "AI-powered"
        ],
        "image": "https://chat.openai.com/docs/assets/images/chatgpt-ml.png",
        "features": [
            "AI chatbot'",
            "Text generation'",
            "Natural language processing'",
            "Natural language understanding'",
            "Generative langua"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "2",
        "name": "ChatGPT",
        "description": "ChatGPT is an AI-powered chatbot that can answer questions and carry out conversations with users. It is trained on vast amounts of text data to generate human-like responses and can be used for a variety of tasks such as answering questions, providing information, and generating content.",
        "category": "Machine Learning",
        "createdAt": 1606694400000,
        "updatedAt": 1675296000000,
        "version": "3.5",
        "rating": 4.5,
        "website": "https://openai.com/product/chatgpt",
        "price": "Free",
        "tags": [
            "Natural language processing",
            "Machine learning",
            "Artificial intelligence",
            "Language generation",
            "Text summarization",
            "Question answering",
            "Content generation",
            "Chatbot",
            "Conversational AI",
            "OpenAI",
            "API",
            "Python",
            "SDK",
            "API key",
            "Platform integration",
            "Data privacy",
            "Language models",
            "Generativ"
        ],
        "image": "https://openai.com/wp-content/uploads/2022/06/whats-new-chatgpt.png",
        "features": [
            " Generate human-like responses to questions a"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "tool7",
        "name": "Monk.ai",
        "description": "Monk.ai enables financial analysts to significantly reduce the time required to analyze financial statements, with minimal effort.",
        "category": "Machine Learning",
        "createdAt": 1589760000000,
        "updatedAt": 1609200000000,
        "version": "1.0",
        "rating": 4,
        "website": "https://www.monk.ai/",
        "price": "Paid",
        "tags": [
            "financial analysis",
            "financial statement analysis",
            "financial analysis automation",
            "financial statement automation",
            "financial analysis AI",
            "financial statement AI",
            "financial analysis software",
            "financial statement"
        ],
        "image": "https://www.monk.ai/wp-content/uploads/2021/05/Monk.ai-new-logo-for-press-and-marketing-300x300.png",
        "features": [
            "Automated financial analysis for financial statements",
            "Automated profitability analysis",
            "Automated financial risk analysis",
            "Automated cash flow analysis",
            "Automated financial statement"
        ],
        "author": "Monk.ai",
        "bookmarked": false
    },
    {
        "id": "308",
        "name": "Google Bard",
        "description": "Google Bard is an AI-powered conversational chatbot that helps users find information, answer questions, and provide assistance in a conversational manner.",
        "category": "Content Creation",
        "createdAt": 891648000000,
        "updatedAt": 1675728000000,
        "version": "1.0",
        "rating": 4.5,
        "website": "https://bard.google.com/",
        "price": "Free",
        "tags": [
            "artificial intelligence",
            "conversational chatbot",
            "language models",
            "natural"
        ],
        "image": "https://lh3.googleusercontent.com/xwuAZu8JuUoSIgDybxSLu0Hm3WJ4V04UjZL-vcMWQRXqWgh_qnT-Hz1h8Y",
        "features": [
            "Conversational AI",
            "description': 'Google Bard is an AI-powered chatbot that can have natural conversations with users.'",
            "Personalized Search",
            "description': 'Google Bard can provide personalized search results based on the user's search "
        ],
        "author": "Google LLC",
        "bookmarked": false
    },
    {
        "id": "111",
        "name": "ChatGPT",
        "description": "ChatGPT is an AI-powered chatbot that can engage in natural language conversations, provide information, and answer questions.",
        "category": "Automation",
        "createdAt": 1606694400000,
        "updatedAt": 1687478400000,
        "version": "2023-05-24 03:00:00",
        "rating": 4.71,
        "website": "https://chat.openai.com/",
        "price": "Free",
        "tags": [
            "chatbot",
            "AI",
            "language model",
            "natural language processing",
            "text generation",
            "conversation",
            "language understanding",
            "chat",
            "question answering",
            "AI chatbot",
            "AI language model",
            "AI assistant",
            "openAI",
            "chatGPT",
            "chatbot"
        ],
        "image": "https://ucarecdn.com/2be60d8d-11f0-498c-8f4c-39d1653f1386/-/scale_crop/1200x602/-/format",
        "features": [
            "Open API",
            "Conversation",
            "OpenAI Models",
            "Customization",
            "Integrations",
            ""
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "45904",
        "name": "Natural Language Understanding",
        "description": "Generates a summary of a text by extracting key information and concepts",
        "category": "Content Creation",
        "createdAt": 1585008000000,
        "updatedAt": 1664064000000,
        "version": "4.2.1",
        "rating": 4.8,
        "website": "https://api.monkeylearn.com/v3/nlutext/summarize/",
        "price": "Paid",
        "tags": [
            "sentiment analysis",
            "text analysis",
            "text classification",
            "text preprocessing",
            "text summarization",
            "text understand"
        ],
        "image": "https://assets.monkeylearn.com/ml-logo.png",
        "features": [
            "Extract key information and concepts from text",
            "Summarise text in a concise and informative manner",
            "Provide insights and analysis of text content",
            "Automatically identify and highlight important phrases and keywords",
            "Analyse and understand the meaning and context of text",
            "Provide contextual a"
        ],
        "author": "MonkeyLearn",
        "bookmarked": true
    },
    {
        "id": "66",
        "name": "GitHub Copilot",
        "description": "GitHub Copilot is a collaborative AI pair-programming tool that can generate code suggestions while you code.",
        "category": "Automation",
        "createdAt": 1625011200000,
        "updatedAt": 1672358400000,
        "version": "2022.8",
        "rating": 4.75,
        "website": "https://copilot.github.com/",
        "price": "Subscription",
        "tags": [
            "AI",
            "automation",
            "code suggestions",
            "code generation",
            "collaborative programming",
            "pair programming",
            "coding",
            "software development",
            "machine learning",
            "artificial intelligence",
            "GitHub Copilot",
            "GitHub",
            "code assistant",
            "code"
        ],
        "image": "https://raw.githubusercontent.com/hitchhiker-inc/copilot-assets/main/img/GitHub%20Copilot%20logo.png",
        "features": [
            "Code suggestions",
            "Code generation",
            "Collaborative programming",
            "Pair programming",
            "Coding",
            "Software development",
            "Machine learning",
            "Artificial intelligence",
            "GitHub Copilot",
            "GitHub",
            "Code assistant",
            "Code c"
        ],
        "author": "GitHub Copilot is a product of GitHub, a subsidiary of Microsoft.",
        "bookmarked": false
    },
    {
        "id": "U878",
        "name": "Bing Chat",
        "description": "An AI tool that provides human-like conversations.",
        "category": "Machine Learning",
        "createdAt": 1678752000000,
        "updatedAt": 1678752000000,
        "version": "Bing Chat",
        "rating": 4.71,
        "website": "https://www.bing.com/chat",
        "price": "Free",
        "tags": [
            "OpenAI",
            "ChatGPT",
            "Bing Chat",
            ""
        ],
        "image": "https://www.bing.com/th?id=OIP.XIqwJ934Xi_U3fD5hMJI7gHaFj&w=316&h=178&c=7&r=0&o=5",
        "features": [
            " AI-powered conversation"
        ],
        "author": "Microsoft Corporation",
        "bookmarked": false
    },
    {
        "id": "165",
        "name": "ChatGPT",
        "description": "ChatGPT is a language model developed by OpenAI that can generate human-like text. It can be used to have conversations with a bot, write blog posts, and answer questions.",
        "category": "Other",
        "createdAt": 1669766400000,
        "updatedAt": 1673395200000,
        "version": "2023-01-11 00:00:00",
        "rating": 4.6,
        "website": "https://chat.openai.com/chat",
        "price": "Free",
        "tags": [
            "language model",
            "text generation",
            "conversation",
            "natural language processing",
            "chatbot",
            "artificial intelligence",
            "machine learning",
            "openai",
            "chatgpt",
            "generative pre-trained tr"
        ],
        "image": "https://github.com/coding-boot-camp/fcc-git-project-lvl1/blob/main/other/chatgpt.png?raw=true",
        "features": [
            "chatbot",
            "text generation",
            "natural language processing",
            "con"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "241",
        "name": "GPT-3",
        "description": "GPT-3 is an autoregressive language model created by OpenAI. It is the third generation of the GPT language model, and it is trained on a dataset of texts that includes both fiction and non-fiction books, articles, and websites.",
        "category": "Machine Learning",
        "createdAt": 1593475200000,
        "updatedAt": 1659312000000,
        "version": "3",
        "rating": 4.4,
        "website": "https://openai.com/api/",
        "price": "Subscription",
        "tags": [
            "AI",
            "natural language processing",
            "generative language model",
            "machine learning",
            "text generation",
            "language model",
            "deep learning",
            "neural networks",
            "text analysis",
            "text generation",
            "language model training",
            "AI development",
            "text analysis and generation",
            "text analysis and"
        ],
        "image": "https://avatars.githubusercontent.com/u/8789044?s=200&v=4",
        "features": [
            "Many languages",
            "Many use cases",
            "Huge",
            "Multilingual",
            "Vast",
            "Powerful",
            "C"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "114",
        "name": "Stable Diffusion 2.1",
        "description": "Stable Diffusion 2.1 is a text-to-image chat AI tool that generates images based on text inputs.",
        "category": "Automation",
        "createdAt": 1669593600000,
        "updatedAt": 1683244800000,
        "version": "2.1",
        "rating": 3.9,
        "website": "https://stability.ai/",
        "price": "Subscription",
        "tags": [
            "image g"
        ],
        "image": "https://stability.ai/img/ghosts.png",
        "features": [
            "Text-to-image g"
        ],
        "author": "StabilityAI",
        "bookmarked": false
    },
    {
        "id": "39",
        "name": "Jasper",
        "description": "Long-form and short-form copywriting tool that helps you write blog posts, sales pages, website copy, product descriptions, and more in seconds with one click.",
        "category": "Content Creation",
        "createdAt": 891388800000,
        "updatedAt": 1675209600000,
        "version": "11.0",
        "rating": 4.2,
        "website": "https://www.jasper.ai/",
        "price": "Subscription",
        "tags": [
            "Content Creation",
            "Copywriting'",
            "Long-form Copywriting'",
            "Short-form Copywriting'",
            "Blog Posts'",
            "Sales Pages'",
            "Website Copy'",
            "Product Descr"
        ],
        "image": "https://www.jasper.ai/assets/images/logo-jasper-ai.png",
        "features": [
            "Long-form and short-form copywriting",
            "Blog posts'",
            "Sales pages'",
            "Website copy'",
            "Product descr"
        ],
        "author": "Jasper",
        "bookmarked": false
    },
    {
        "id": "Tool_143",
        "name": "Perplexity",
        "description": "A measure of the randomness or complexity of a sequence of numbers",
        "category": "Machine Learning",
        "createdAt": 1659484800000,
        "updatedAt": 1659484800000,
        "version": "0.1.0",
        "rating": 3.71,
        "website": "https://www.perplexity.ai/",
        "price": "Free",
        "tags": [
            "complexity",
            "randomness",
            "machine learning",
            "sequence",
            "numbers",
            "artificial int"
        ],
        "image": "https://www.perplexity.ai/img/logo.png",
        "features": [
            "Randomness of a sequence of numbers",
            "Complexity of a sequence o"
        ],
        "author": "'Perplexity.ai is a free web-based tool that uses machine learning algorithms to measure the randomness or complexity of a sequence of numbers. The tool is developed by a team of researchers interested in machine learning and artificial intelligence, including Dr. Andrew Ng, founder of Coursera and former chief scientist at",
        "bookmarked": false
    },
    {
        "id": "Tool_263",
        "name": "Visual AI",
        "description": "Visual AI is an AI-powered tool that can detect and recognize objects, people, and scenes in images and videos. It can also generate captions and descriptions for images and videos.",
        "category": "Machine Learning",
        "createdAt": -33004800000,
        "updatedAt": 1676419200000,
        "version": "1.0.0",
        "rating": 4.7,
        "website": "https://www.google.com/visual-ai/",
        "price": "Free",
        "tags": [
            "image recognition",
            "object detection",
            "scene detection",
            "image captioning",
            "image description",
            "image annotation",
            "image class"
        ],
        "image": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
        "features": [
            "image recognition",
            "object detection",
            "scene detection",
            "image captioning",
            "image de"
        ],
        "author": "Google LLC",
        "bookmarked": false
    },
    {
        "id": "50",
        "name": "WolframAlpha",
        "description": "Wolfram|Alpha is a computational knowledge engine that answers factual queries directly by computing the answer from publicly available data and other sources.",
        "category": "Data Analysis",
        "createdAt": 1242345600000,
        "updatedAt": 1624406400000,
        "version": "9.5.185",
        "rating": 4.2,
        "website": "https://www.wolframalpha.com/",
        "price": "Subscription",
        "tags": [
            "Wolfram Alpha",
            "Mathematics",
            "Computational",
            "Knowledge",
            "Engine",
            "Symbolic",
            "Mathematical",
            "Data",
            "Derivative",
            "Graph",
            "Equation",
            "Function",
            "Integral",
            "Simplify",
            "Solve",
            "Differential",
            "Equations",
            "Plots",
            "Trigonometric"
        ],
        "image": "https://img.icons8.com/fluency/48/000000/wolfram-alpha.png",
        "features": [
            "Derivative",
            "Graph",
            "Equation",
            "Function",
            "Integral",
            "Simplify",
            "Solve",
            "Differential Equations",
            "Plots",
            "Trigonometric",
            "Geomet"
        ],
        "author": "Wolfram|Alpha LLC",
        "bookmarked": false
    },
    {
        "id": "TOOL_06710",
        "name": "Replika",
        "description": "Replika is an AI-powered app that offers virtual companions for users. It uses natural language processing and machine learning algorithms to create a personalized virtual friend that can engage in conversations with users and provide emotional support.",
        "category": "Other",
        "createdAt": 1496275200000,
        "updatedAt": 1627862400000,
        "version": "AI Companion 2.6.14",
        "rating": 3.6,
        "website": "https://replika.ai/",
        "price": "Subscription",
        "tags": [
            "chat",
            "chatbot",
            "ai",
            "virtual",
            "companion",
            "emotional",
            "support",
            "con"
        ],
        "image": "https://storage.googleapis.com/prerender-s3/initial/7614586995381877278.png",
        "features": [
            "Conversation",
            "Emotional Support",
            "Personalization",
            "Customization",
            "Privacy",
            ""
        ],
        "author": "Replika AI LLC",
        "bookmarked": false
    },
    {
        "id": "K2H3FLH0155",
        "name": "Dall-E",
        "description": "Dall-E is an artificial intelligence tool that generates images based on textual descriptions.",
        "category": "Other",
        "createdAt": 1618358400000,
        "updatedAt": 1647907200000,
        "version": "v1",
        "rating": 0,
        "website": "https://openai.com/blog/dall-e/",
        "price": "Subscription",
        "tags": [
            "Image g"
        ],
        "image": "https://d2c6u8m1ud8yb3.cloudfront.net/openai-2022-02-16-499f700c-39b9-4d09-b61d-57263",
        "features": [
            "Image g"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "08006",
        "name": "AIVA",
        "description": "AIVA is an AI-based music composition platform that generates MIDI files in various genres, including classical, jazz, and pop.",
        "category": "Automation",
        "createdAt": 1526256000000,
        "updatedAt": 1619395200000,
        "version": "4.0",
        "rating": 4,
        "website": "https://aiva.ai/",
        "price": "Subscription",
        "tags": [
            "music",
            "AI",
            "composition",
            "MIDI",
            "automation",
            "AI-based",
            "classical",
            ""
        ],
        "image": "https://aiva.ai/wp-content/uploads/2019/09/music-generator-ai.png",
        "features": [
            "Automatic music composition",
            "MIDI fi"
        ],
        "author": "AIVA",
        "bookmarked": false
    },
    {
        "id": "1",
        "name": "ChatGPT",
        "description": "ChatGPT is a Large Language Model (LLM) developed by OpenAI. It is a conversational AI tool that can generate human-like responses to various inputs.",
        "category": "Content Creation",
        "createdAt": 0,
        "updatedAt": 1684108800000,
        "version": "2023-04-27",
        "rating": 4.62,
        "website": "https://openai.com/product/chatgpt",
        "price": "Free",
        "tags": [
            "natural language processing",
            "language generation",
            "conversational AI",
            "chatbot",
            "machine learning",
            "artificial intelligence",
            "generative pre-trained transformer",
            "GPT",
            "langu"
        ],
        "image": "https://openai.com/wp-content/uploads/2023/04/GPT4-Logo-1.png",
        "features": [
            "generative pre-trained transformer",
            "GPT",
            "large language model",
            "natural language processing",
            "language generation",
            "conversational AI",
            "chatbot",
            "machine learning",
            "artificial int"
        ],
        "author": "Creator or Company: OpenAI",
        "bookmarked": false
    },
    {
        "id": "1034",
        "name": "ChatGPT",
        "description": "ChatGPT is an AI language model that can understand and generate human-like text. It can be used to create chatbots, generate content for websites or social media, and assist with a variety of tasks, such as answering questions, summarizing information, and writing essays.",
        "category": "Machine Learning",
        "createdAt": 1604534400000,
        "updatedAt": 1625529600000,
        "version": "API",
        "rating": 3.1,
        "website": "https://chat.openai.com/chat",
        "price": "Subscription",
        "tags": [
            "AI language model",
            "chatbot",
            "content creation",
            "information summarization",
            "essay writing",
            "question answering",
            "natural language processing",
            "machine learning",
            "language generation",
            "conversation generation",
            "chatbot creation",
            "content generation",
            "text summarization",
            "essay writing"
        ],
        "image": "https://image.shutterstock.com/image-photo/chatbot-concept-login-screen-chat-260nw-1000836164.jpg",
        "features": [
            "Conversation Generation",
            "Natural Language Processing",
            "Language Generation",
            "Chatbot Creation",
            "Content Generation",
            "Text Summarization",
            "Image Generator",
            "Essay Writing A"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "168",
        "name": "ChatGPT",
        "description": "ChatGPT is a natural language processing (NLP) tool developed by OpenAI that allows users to interact with artificial intelligence (AI) in a conversational manner. It uses machine learning algorithms to generate human-like responses to text-based inputs, enabling users to have natural conversations with the AI.",
        "category": "Machine Learning",
        "createdAt": 1604275200000,
        "updatedAt": 1613260800000,
        "version": "2022-05-30 00:00:00",
        "rating": 4.8,
        "website": "https://openai.com/blog/chatgpt/",
        "price": "Free",
        "tags": [
            "natural language processing",
            "machine learning",
            "artificial intelligence",
            "conversational AI",
            "language g"
        ],
        "image": "https://openai.com/wp-content/uploads/2021/01/ChatGPT-scaled.png",
        "features": [
            "natural language processing",
            "machine learning",
            "artificial intelligence",
            "conversational AI",
            "language g"
        ],
        "author": "Creator: OpenAI",
        "bookmarked": false
    },
    {
        "id": "25",
        "name": "ChatGPT",
        "description": "ChatGPT is an AI tool for interactive conversations.",
        "category": "Other",
        "createdAt": 1605830400000,
        "updatedAt": 1681430400000,
        "version": "v1.0.0.3",
        "rating": 4.3,
        "website": "https://chat.openai.com/chat",
        "price": "Free",
        "tags": [
            "Natural language processing",
            "Artificial intelligence",
            "Machine learning",
            "Text generation",
            "Conversational AI",
            "Chatbot",
            "Language model",
            "OpenAI",
            "ChatGPT",
            "AI wri"
        ],
        "image": "https://huggingface.co/datasets/UW-NLP/chinese-gpt2-xl/resolve/main/image.png",
        "features": [
            "Interactive natural language con"
        ],
        "author": "Contact: OpenAI",
        "bookmarked": false
    },
    {
        "id": "166",
        "name": "HumanAi",
        "description": "Large Language Model for creating Human-like conversation",
        "category": "Data Analysis",
        "createdAt": 1650067200000,
        "updatedAt": 1650067200000,
        "version": "0.14.1",
        "rating": 4.62,
        "website": "https://humanai.dev/",
        "price": "Free",
        "tags": [
            "AI chatbot",
            "human-like conversation",
            "NLP",
            "large language model",
            ""
        ],
        "image": "https://humanai.dev/humanai/img/logo.png",
        "features": [
            "A Large Language Model for creating Human-like conversation",
            "Over 30",
            "000 of Human-like conve"
        ],
        "author": "HumanAi",
        "bookmarked": false
    },
    {
        "id": "2746",
        "name": "ChatGPT",
        "description": "ChatGPT is a language model developed by OpenAI that can be used to generate human-like text. It is trained on a large amount of text data and can be used for a variety of tasks such as answering questions, generating text, and translating between languages.",
        "category": "Data Analysis",
        "createdAt": 86400000000,
        "updatedAt": 1678752000000,
        "version": "ChatGPT",
        "rating": 4.9090909091,
        "website": "https://openai.com/blog/chatgpt/",
        "price": "Free",
        "tags": [
            "chatbot",
            "score': 0.545928",
            "language model",
            "score': 0.410213",
            "natural language processing",
            "score': 0.3698"
        ],
        "image": "https://openai.com/blog/wp-content/uploads/2022/12/chatgpt_2.jpeg",
        "features": [
            "natural language processing",
            "conversational AI",
            "text generation",
            "question answering",
            "langu"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "10",
        "name": "ChatGPT",
        "description": "ChatGPT, developed by OpenAI, is a large language model based on state-of-the-art natural language processing (NLP) technology, trained by the company to assist in a wide range of natural language processing tasks.",
        "category": "Machine Learning",
        "createdAt": 374630400000,
        "updatedAt": 1678752000000,
        "version": "3.5",
        "rating": 4.6,
        "website": "https://openai.com/blog/chatgpt/",
        "price": "Subscription",
        "tags": [
            "artificial intelligence",
            "natural language processing",
            "chatbot",
            "machine learning",
            "language model",
            "sentiment analysis",
            "text generation",
            "question answering",
            "conversational AI",
            "chatbot technology",
            "natural language understanding",
            "text class"
        ],
        "image": "https://openai.com/img/branding/chatgpt.png",
        "features": [
            "Chatbot",
            "Natural Language Processing",
            "Machine Learning",
            "Language Model",
            "Text Generation",
            "Question Answering",
            "Conversa"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "5",
        "name": "Writesonic",
        "description": "Writesonic is an AI-powered writing tool that helps you to create high-quality content in seconds.",
        "category": "Content Creation",
        "createdAt": 1620604800000,
        "updatedAt": 1678838400000,
        "version": "2.0",
        "rating": 4.7,
        "website": "https://app.writesonic.com/",
        "price": "Subscription",
        "tags": [
            "AI writing assistant",
            "content generation",
            "copywriting",
            "marketing automation",
            "SEO optimization",
            "social media m"
        ],
        "image": "https://external-preview.redd.it/Cg5T3D2Qfk6G6W7_6Oj00Km52kUZVX5Z75G8109_cG3tF32N3Ij_y",
        "features": [
            "Chatbot",
            "Natural Language Processing",
            "Machine"
        ],
        "author": "Founded in 2021 by Joshua Fletcher, Writesonic is an AI-powered writing tool that helps you to create high-quality content in seconds. With Writesonic, you can generate blog posts, web copy, social media content, and more with just a few clicks.",
        "bookmarked": false
    },
    {
        "id": "522",
        "name": "Twitter ChatBot",
        "description": "Twitter Chat Bot is an AI tool that generates personalized responses to user 's tweets by analyzing their interests and preferences.",
        "category": "Machine Learning",
        "createdAt": 1462924800000,
        "updatedAt": 1566518400000,
        "version": "0.1",
        "rating": 4.4,
        "website": "https://twitter.com/TwitterChatBot",
        "price": "Paid",
        "tags": [
            "Twitter",
            "Chat Bot",
            "Artificial Intelligence",
            "Machine Learning",
            "Twitter ChatBot",
            "AI",
            "Chat Bot",
            "Twitter Chat Bot",
            "Chat Bot for Twitter",
            "AI"
        ],
        "image": "https://twittersocialbot.com/wp-content/uploads/2020/02/TwitterSocialBot.png",
        "features": [
            "Twitter ChatBot",
            "Twitter Chat Bot",
            "Twitter ChatBot",
            "Twitter Chat Bot",
            "Twitter"
        ],
        "author": "Created by Twitter Social Bot LLC",
        "bookmarked": true
    },
    {
        "id": "G1001",
        "name": "ChatGPT",
        "description": "ChatGPT is an AI language model developed by OpenAI that enables users to have real-time conversations with a chatbot. It can answer a wide range of questions and generate human-like responses to natural language inputs.",
        "category": "Content Creation",
        "createdAt": 1575158400000,
        "updatedAt": 1622505600000,
        "version": "'2021-06-01 00:00:00'",
        "rating": 4.5,
        "website": "https://chat.openai.com/chat",
        "price": "Free",
        "tags": [
            "chatbot",
            "language model",
            "conversation",
            "natural language processing",
            "artificial int"
        ],
        "image": "https://cdn.worldvectorlogo.com/logos/chatgpt-2.svg",
        "features": [
            "Chatbot",
            "Language Model",
            "Conversation",
            "Natural Language Processing",
            "Artificial Int"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "14",
        "name": "Stable Diffusion",
        "description": "A text-to-image AI tool that uses a generative adversarial network (GAN) to create images from text descriptions.",
        "category": "Content Creation",
        "createdAt": 1652313600000,
        "updatedAt": 1663027200000,
        "version": "v1.4",
        "rating": 4.8824577462,
        "website": "https://huggingface.co/spaces/CompVis/stable-diffusion-webui",
        "price": "Paid",
        "tags": [
            "stable diffusion",
            "text to image",
            "generative adversarial network",
            "GAN",
            "artificial intelligence",
            "AI",
            "content creation",
            "cr"
        ],
        "image": "https://huggingface.co/CompVis/stable-diffusion-webui/tree/main/_static/screenshots/webui_20220828_144649.png",
        "features": [
            "Text-to-image AI generator",
            "Generative adversarial network (GAN)",
            "Artistic image style transfer",
            "Generative image creation",
            "Stylized image generation",
            "Image enhancement",
            "Realistic image rendering",
            "Image man"
        ],
        "author": "Creator - Stability AInCompany - Stability AInEmail - [email protected]nWebsite - https://stability.ai/n",
        "bookmarked": false
    },
    {
        "id": "AS21484",
        "name": "ChatGPT",
        "description": "ChatGPT is a state-of-the-art language model developed by OpenAI. It has been trained on a large dataset of text and is capable of generating human-like responses to natural language inputs.",
        "category": "Machine Learning",
        "createdAt": 879552000000,
        "updatedAt": 1678752000000,
        "version": "3.5",
        "rating": 4.4478,
        "website": "https://chat.openai.com/chat",
        "price": "Subscription",
        "tags": [
            "natural language processing",
            "language modeling",
            "text generation",
            "conversation",
            "chatbot",
            "openai",
            ""
        ],
        "image": "https://miro.medium.com/max/1400/1*ZbQx2B0hF9FbK3gxhm9gmw.png",
        "features": [
            "natural language processing",
            "language modeling",
            "text generation",
            "conversation",
            ""
        ],
        "author": "OpenAI",
        "bookmarked": true
    },
    {
        "id": "613",
        "name": "ChatGPT",
        "description": "An AI-powered conversational agent that can carry out natural language interactions and provide a wide range of responses to a variety of text-based inputs.",
        "category": "Content Creation",
        "createdAt": 57801600000,
        "updatedAt": 1678752000000,
        "version": "1.4.3",
        "rating": 4.8,
        "website": "https://openai.com/product/chatgpt",
        "price": "Free",
        "tags": [
            "ChatGPT",
            "score': 0.7380183567059326",
            "LLM",
            "score': 0.25852141939651"
        ],
        "image": "https://openai.com/assets/images/chatgpt-logo.svg",
        "features": [
            "Conversational AI",
            "Customizable responses",
            "Integration with other tools",
            "Continuous learning and improvement",
            "Text-based interactions",
            "Personalized responses",
            "Natural language processing",
            "Multilingual support",
            "Text summarization",
            "Text tr"
        ],
        "author": "OpenAI",
        "bookmarked": true
    },
    {
        "id": "21",
        "name": "Bert",
        "description": "BERT is a natural language processing model that uses transformer architecture and is pre-trained on a large amount of text data. It is often used for tasks such as language understanding, sentiment analysis, and natural language generation.",
        "category": "Machine Learning",
        "createdAt": 1541030400000,
        "updatedAt": 1653177600000,
        "version": "2.0.5",
        "rating": 4.6,
        "website": "https://huggingface.co/transformers/model_doc/bert.html",
        "price": "Paid",
        "tags": [
            "pre-training",
            "natural language processing",
            "language understanding",
            "sentiment analysis",
            "natural language generation",
            "transformer",
            "transformer architecture",
            "large amount of "
        ],
        "image": "https://huggingface.co/transformers/assets/img/transformers_logo.svg",
        "features": [
            "pre-training",
            "natural language processing",
            "language understanding",
            "sentiment analysis",
            "natural language generation",
            "transformer",
            "transformer architecture",
            "large amount of "
        ],
        "author": "Stanford University and Google",
        "bookmarked": false
    },
    {
        "id": "269",
        "name": "GitHub Copilot",
        "description": "AI-assisted code generation tool",
        "category": "Machine Learning",
        "createdAt": 1636329600000,
        "updatedAt": 1679961600000,
        "version": "2023.7",
        "rating": 3.6,
        "website": "https://github.com/features/copilot",
        "price": "Subscription",
        "tags": [
            "artificial intelligence",
            "machine learning",
            "software development",
            "code g"
        ],
        "image": "https://user-images.githubusercontent.com/106436694/235097777-034d85d4-e7b0-4a2a-80f8-a41b9999",
        "features": [
            "AI-assisted code generation",
            "Code completion",
            "Code refactoring",
            "Code suggestion",
            "Documentation generation",
            "Language translation",
            "Code debugging",
            "Code optimization",
            "Code verification",
            "Code analysis",
            "Code generation",
            "Code suggestion",
            "Code completion",
            ""
        ],
        "author": "Copilot is a code generation tool developed by GitHub, a software development platform owned by Microsoft.",
        "bookmarked": true
    },
    {
        "id": "2787",
        "name": "Transcribe AI",
        "description": "Transcribe AI is a powerful AI-powered tool that offers speech-to-text transcription services. It uses advanced speech recognition algorithms to convert audio files into text, making it easy to transcribe audio recordings and interviews.",
        "category": "Automation",
        "createdAt": 1603238400000,
        "updatedAt": 1680912000000,
        "version": "v1.2",
        "rating": 4.9,
        "website": "https://transcribe-ai.com/",
        "price": "Subscription",
        "tags": [
            "ranscription",
            "speech-to-text",
            "audio files",
            "text",
            "interviews",
            "AI-powered",
            "advanced speech recognition algorithms",
            "audio recordings",
            "transcriptio"
        ],
        "image": "https://transcribe-ai.com/img/transcribe-ai-logo.png",
        "features": [
            "Advanced Speech Recognition Algorithms",
            "Multilingua"
        ],
        "author": "Transcribe AI",
        "bookmarked": false
    },
    {
        "id": "167",
        "name": "Text Blender 6.2",
        "description": "Text Blender is an AI-powered tool that generates new text passages based on the existing text. It can be used to enhance the existing text or to create new content that is similar in style and tone.",
        "category": "Content Creation",
        "createdAt": 1648771200000,
        "updatedAt": 1656633600000,
        "version": "6.2",
        "rating": 4.61,
        "website": "https://textblender.com",
        "price": "Subscription",
        "tags": [
            "content creation",
            ""
        ],
        "image": "https://textblender.com/assets/img/icon-textblender.svg",
        "features": [
            "Generate new text passages based on the existing text",
            "Enhance the existing text",
            "Create new content that is similar in style"
        ],
        "author": "Text Blender",
        "bookmarked": false
    },
    {
        "id": "tool_21",
        "name": "Whisper",
        "description": "Whisper is a text-to-speech model that can convert text into speech.",
        "category": "Machine Learning",
        "createdAt": 922924800000,
        "updatedAt": 1685577600000,
        "version": "v1.15.1",
        "rating": 4.59,
        "website": "https://openai.com/blog/whisper/",
        "price": "Free",
        "tags": [
            "speech-to-text",
            "text-to-speech",
            "natural language processing",
            "machine learning",
            "artificial intelligence",
            "natural language understanding",
            "neural"
        ],
        "image": "https://cdn.openai.com/assets/machine-learning-solutions/openai-whisper-79070616cd7e179697589782c111d08b.png",
        "features": [
            "Natural language processing",
            "Machine learning",
            "Artificial intelligence",
            "Natural language understanding",
            "Neural"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "Tool_179",
        "name": "TextBlade",
        "description": "AI-based tool that generates personalized content",
        "category": "Content Creation",
        "createdAt": 757382400000,
        "updatedAt": 1627171200000,
        "version": "v0.1",
        "rating": 4.9,
        "website": "https://textblade.com/",
        "price": "Paid",
        "tags": [
            "Text generation",
            "content creation",
            "personalized content",
            "AI-b"
        ],
        "image": "https://textblade.com/images/logos/text-blade-logo-accent.png",
        "features": [
            "AI-based text generation",
            "Personalized content creation",
            "Customizable content options",
            "Content optimization",
            "Text"
        ],
        "author": "TextBlade, Inc.",
        "bookmarked": false
    },
    {
        "id": "'779'",
        "name": "Bella",
        "description": "A photo collage maker",
        "category": "Content Creation",
        "createdAt": 1640044800000,
        "updatedAt": 1641081600000,
        "version": "1.0.1",
        "rating": 4.5,
        "website": "https://www.bellascollages.com",
        "price": "Paid",
        "tags": [
            "photo coll"
        ],
        "image": "https://pbs.twimg.com/media/FJj5Zb9WUAQ9x3Q?format=jpg&name=small",
        "features": [
            "ease of use",
            "creativity",
            "customization",
            ""
        ],
        "author": "Bella is a product of Photovisi, a team of photo editing enthusiasts.",
        "bookmarked": false
    },
    {
        "id": "716",
        "name": "NovelAI",
        "description": "Artificial Intelligence tool for generating original art using text prompts.",
        "category": "Machine Learning",
        "createdAt": 404956800000,
        "updatedAt": 1684108800000,
        "version": "v0.6.2",
        "rating": 4.5,
        "website": "https://www.novelai.net/",
        "price": "Subscription",
        "tags": [
            "art",
            "AI",
            "original art",
            "text prompt",
            "gene"
        ],
        "image": "https://novelai.net/wp-content/uploads/2022/08/beautiful-girl-anime.jpg",
        "features": [
            " 'Original Art'",
            "description': 'Generate original art using text prompts'",
            "Machine Learning",
            "description': 'Powered by machine learning a"
        ],
        "author": "NovelAI",
        "bookmarked": false
    },
    {
        "id": "479",
        "name": "Audio to Text",
        "description": "Automatically converts an audio file into a text format.",
        "category": "Other",
        "createdAt": 1554422400000,
        "updatedAt": 1592265600000,
        "version": "0.5.6",
        "rating": 4.8,
        "website": "https://www.speechtools.io/",
        "price": "Subscription",
        "tags": [
            "audio file",
            "text format",
            "automatically",
            "converts",
            "audio",
            "text",
            "tool",
            "conversion",
            "audio files",
            "audi"
        ],
        "image": "https://img.icons8.com/ios-glyphs/16/000000/microphone.png",
        "features": [
            " Converts Audio"
        ],
        "author": "SpeechTools",
        "bookmarked": false
    },
    {
        "id": "T12051",
        "name": "Ai-GPT",
        "description": "a natural language processing (nlp) tool that is able to generate text based on a given input",
        "category": "Machine Learning",
        "createdAt": 1586822400000,
        "updatedAt": 1670803200000,
        "version": "1.4.5",
        "rating": 4.6,
        "website": "https://platform.openai.com/",
        "price": "Paid",
        "tags": [
            "OpenAI API",
            "GPT-3.5 language model",
            "Chat",
            "GPT-4 language model",
            "ChatCompletion",
            "Text-Davinci-003 model",
            "Codex",
            "Image G"
        ],
        "image": "https://platform.openai.com/assets/images/openai-logo-white-1f08ac9b55f93681b8731354f962a3eb8607475e3968a5",
        "features": [
            "OpenAI API",
            "GPT-3.5 language model",
            "Chat",
            "GPT-4 language model",
            "ChatCompletion",
            "Text-Davinci-003 model",
            "Codex",
            "Image G"
        ],
        "author": "OpenAI",
        "bookmarked": true
    },
    {
        "id": "897",
        "name": "text-generation-2022-07-26-20-39-12",
        "description": "Generates text",
        "category": "Content Creation",
        "createdAt": 1658793600000,
        "updatedAt": 1666742400000,
        "version": "1.0",
        "rating": 4.61,
        "website": "https://huggingface.co/docs/transformers/main/en/model_doc/hub/text-generation",
        "price": "Free",
        "tags": [
            "text-g"
        ],
        "image": "https://huggingface.co/docs/transformers/main/en/model_doc/hub/text-generation",
        "features": [
            "Text g"
        ],
        "author": "Hugging Face",
        "bookmarked": false
    },
    {
        "id": "22",
        "name": "ChatGPT",
        "description": "ChatGPT is a language model developed by OpenAI that is capable of conversational interactions with human users. It uses deep learning techniques to generate human-like responses based on the input it receives. The tool is designed to help users with various tasks, such as answering questions, providing information, and generating text.",
        "category": "Machine Learning",
        "createdAt": 1606694400000,
        "updatedAt": 1670889600000,
        "version": "v1.0",
        "rating": 4.8,
        "website": "https://chat.openai.com/",
        "price": "Free",
        "tags": [
            "natural language processing",
            "chatbot",
            "conversational AI",
            "text generation",
            "language models",
            "deep learning",
            "machine learning",
            "chatbot technologies",
            "language analytics",
            "artificial int"
        ],
        "image": "https://raw.githubusercontent.com/open-source-ai-tools/ai-tool-images/main/2.jpg",
        "features": [
            "Conversational AI",
            "Text Generation",
            "Natural Language P"
        ],
        "author": "OpenAI",
        "bookmarked": false
    },
    {
        "id": "1120",
        "name": "Clarifai",
        "description": "Clarifai is a computer vision and artificial intelligence platform that provides advanced image recognition and classification capabilities. It uses deep learning algorithms to analyze images and videos and can detect objects, people, scenes, and more in real-time.",
        "category": "Machine Learning",
        "createdAt": 1380585600000,
        "updatedAt": 1654473600000,
        "version": "2.5.0",
        "rating": 4.9,
        "website": "https://www.clarifai.com/",
        "price": "Subscription",
        "tags": [
            "mage recognition",
            "computer vision",
            "deep learning",
            "machine learning",
            "artificial intelligence",
            "classification",
            "real-time",
            "object detection",
            "scene detection",
            "facial recognition",
            "image analysis",
            "image classification",
            "image recognition API",
            "image an"
        ],
        "image": "https://www.clarifai.com/wp-content/uploads/2021/07/A-Path-to-a-Sustainable-Future-with-AI.png",
        "features": [
            "Computer Vision",
            "Image Recognition",
            "Machine Learning",
            "Artificial Intelligence",
            "Deep Learning",
            "Image Classification",
            "Image Analysis",
            "Object Detection",
            "Scene Detection",
            "Facial Re"
        ],
        "author": "Creator: Clarifai",
        "bookmarked": false
    }
]

export default data